### PR TITLE
v2.1.50 blank editor bug workaround

### PR DESCRIPTION
**Pull request by BlueGreenMagick**
https://forums.ankiweb.net/t/2-1-50-editor-wont-show-when-addons-load-many-js-files/19036

### CODE REVIEW

**Comment by AnKingMed** [comment]
I think this was resolved..  Do we need to merge this or are we good to just close this?

**Comment by BlueGreenMagick** [comment]
Depends. It should be fixed in 2.1.52+, but still broken in 2.1.50-51. It's a question of if you need the add-on to still work on those two versions.

**Comment by AnKingMed** [comment]
In that case it wouldn't hurt to merge it then would it?

**Comment by BlueGreenMagick** [comment]
I think so? The only problem I can think of is if some other editor add-on inserts invalid HTML, this add-on will stop working.

Should I merge it then?

**Comment by AnKingMed** [comment]
It looks like there are some conflicts. Do you have permissions to just go ahead and merge this PR?  It's sad, but I don't actually know how to resolve conflicts in a PR yet 😂

**Comment by BlueGreenMagick** [comment]
Yeah, resolving merge conflict is no joke. It always takes a couple of tries for me as well

**Comment by AnKingMed** [comment]
I merged this in and now it won't let me create a new version. Any idea why?

**Comment by AnKingMed** [comment]
nevermind.. I just typed the version in on accident :p

**Pull request merged**
