### PR TITLE
Add button for proper styling of mnemonics

### PR DESCRIPTION
**Pull request by shmuelsash**
Uses "wrap" action to apply `<div class="mnemonics">` before selected text and `</div>` after selected text

Icon png is from [here](https://commons.wikimedia.org/wiki/File:Noun_Project_lightbulb_icon_1263005_cc.svg)

### CODE REVIEW

**Comment by abdnh** [comment]
Is this intended for use with lists? It gives weird results there though.

image

**Comment by shmuelsash** [comment]
Technically they're lists but they don't have the  `ul` or `li` tags, it's just text on a new line

What's weird about it?

**Comment by abdnh** [comment]
> What's weird about it?

The div doesn't wrap the whole `ul` tag, and it messes up the list formatting. Shouldn't be a problem if this won't be used with HTML lists.

**Comment by shmuelsash** [comment]
Yeh mnemonics aren't lists

**Pull request merged**
