### PR TITLE
Add button to blur images

### PR DESCRIPTION
**Pull request by abdnh**
See https://github.com/AnKing-VIP/AnKing-Note-Types/issues/148 for context.

This adds a button to blur selected images. It works for non-AnKing note types too because the basic CSS styles (just `filter: blur(15px)`) are added by the add-on to the template.

image

@AnKingMed

### CODE REVIEW

**Comment by shmuelsash** [comment]
Instead of adding it to the Wrapper meta addon wouldn't it more user friendly if we added an option in the dropdown menu when you right click the image

I have a couple of addons that do that already
image

**Comment by abdnh** [comment]
@AnKingMed what do you think about @shmuelsash's suggestion? I personally like the button more, as it works for all selected images, and might be simpler to implement.

**Comment by AnKingMed** [comment]
I think that's reasonable. Would we just implement that from the AnKing Note Types add-on? Maybe that's the best solution

**Comment by abdnh** [comment]
> Would we just implement that from the AnKing Note Types add-on? Maybe that's the best solution

Yes. I'll close this PR then.

**Pull request closed without merging**
